name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/dump
        with:
          enable-context: "true"
      - run: echo "{$DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}